In [ ]:
import numpy as np

In [ ]:
def RelU(x, derivative=False):
    if derivative:
        x = np.where(x < 0, 0, x)
        x = np.where(x >= 0, 1, x)
        return x
    return np.maximum(0, x)

def Sigmoid(x):
  return 1 / (1 + np.exp(-x))


In [ ]:
learning_rate = 0.1

W1 = np.array([[0.17,0.26],[0.37,0.46],[0.57,0.46]])
W2 = np.array([[7.15,7.25,7.35],[6.45,6.55,6.65]])
W3 = np.array([[42.12,42.22],[42.32,42.42],[42.52,42.62]])
W4 = np.array([[1.16],[1.36]])

b1 = np.array([[0.71],[0.62]])
b2 = np.array([[13.15],[13.25],[13.35]])
b3 = np.array([[1.12],[1.22]])
b4 = np.array([[-0.74]])

X1 = np.array([[7],[6],[7]])
Y1 = np.array([[7]])
X2 = np.array([[6],[7],[6]])
Y2 = np.array([[6]])


In [ ]:
def forward_prop(W1,b1,W2,b2,W3,b3,W4,b4,X):
  A1 = np.matmul(W1,X) + b1
  Z = np.tanh(A1)
  A2 = np.matmul(W2,Z) + b2
  K = Sigmoid(A2)
  A3 = np.matmul(W3,K) + b3
  P = np.tanh(A3)
  A4 = np.matmul(W4,P) + b4
  yhat = RelU(A4)
  return A1,Z,A2,K,A3,P,A4,yhat

def back_prop(W1,B1,W2,B2,W3,B3,W4,B4,X,Y,A1,Z,A2,K,A3,P,A4,yhat,alpha):
  # W4, B4
  dEdy = yhat - Y
  dydA4 = A4 > 0 
  B4, W4, dEdA4 = update(B4, W4, dEdy, dydA4, P, alpha)
  # W3, B3
  dEdP = dE_dal_1(W4 , dEdA4)
  dPdA3 = 1 - P**2
  B3, W3, dEdA3 = update(B3, W3, dEdP, dPdA3, K, alpha)
  # W2, B2
  dEdK = dE_dal_1(W3 , dEdA3)
  dKdA2 = K * (1-K)
  B2, W2, dEdA2 = update(B2, W2, dEdK, dKdA2, Z, alpha)
  # W1, B1
  dEdZ = dE_dal_1(W2 , dEdA2)
  dZdA1 = 1 - Z**2
  B1, W1, _ = update(B1, W1, dEdZ, dZdA1, X, alpha)
  return W1, B1, W2, B2, W3, B3, W4, B4
  
def dE_dAl(dE_da, da_dA):
  return dE_da * da_dA

def dE_dWl(dE_dA, a):
  return (dE_dA) @ a.T

def dE_dal_1(W , dE_dA):
  return W.T @ dE_dA 

def dE_dBl(dE_dA):
  return dE_dA

def SD(x, dx, eta):
  return x - eta * dx

def update(B, W, dE_da, da_dA, a, eta):
  dE_dA = dE_dAl(dE_da, da_dA)
  dE_dB = dE_dBl(dE_dA)
  dE_dW = dE_dWl(dE_dA, a)
  B = SD(B, dE_dB, eta)
  W = SD(W, dE_dW, eta)
  return B, W, dE_dA

def transpose(W1,W2,W3,W4):
  W1,W2,W3,W4 = W1.T,W2.T,W3.T,W4.T
  return W1,W2,W3,W4

def printing(W_1,b1,W_2,b2,W_3,b3,W_4,b4):
  print("W1: ",W_1)
  print("B1: ",b1)
  print("W2: ",W_2)
  print("B2: ",b2)
  print("W3: ",W_3)
  print("B3: ",b3)
  print("W4: ",W_4)
  print("B4: ",b4)


In [ ]:
alpha = 0.1
W_1,W_2,W_3,W_4 = transpose(W1,W2,W3,W4)
print("initial values:")
printing(W_1, b1, W_2, b2, W_3, b3, W_4, b4)
print("#################################")
A1,Z,A2,K,A3,P,A4,yhat = forward_prop(W_1,b1,W_2,b2,W_3,b3,W_4,b4,X1)
W_1, B1, W_2, B2, W_3, B3, W_4, B4 = back_prop(W_1,b1,W_2,b2,W_3,b3,W_4,b4,X1,Y1,A1,Z,A2,K,A3,P,A4,yhat,alpha)
print("first iteration:")
printing(W_1, B1, W_2, B2, W_3, B3, W_4, B4)
print("#################################")
A1,Z,A2,K,A3,P,A4,yhat = forward_prop(W_1,B1,W_2,B2,W_3,B3,W_4,B4,X2)
W_1, B1, W_2, B2, W_3, B3, W_4, B4 = back_prop(W_1,B1,W_2,B2,W_3,B3,W_4,B4,X2,Y2,A1,Z,A2,K,A3,P,A4,yhat,alpha)
print("second iteration:")
printing(W_1, B1, W_2, B2, W_3, B3, W_4, B4)
print("#################################")

initial values:
W1:  [[0.17 0.37 0.57]
 [0.26 0.46 0.46]]
B1:  [[0.71]
 [0.62]]
W2:  [[7.15 6.45]
 [7.25 6.55]
 [7.35 6.65]]
B2:  [[13.15]
 [13.25]
 [13.35]]
W3:  [[42.12 42.32 42.52]
 [42.22 42.42 42.62]]
B3:  [[1.12]
 [1.22]]
W4:  [[1.16 1.36]]
B4:  [[-0.74]]
#################################
first iteration:
W1:  [[0.17 0.37 0.57]
 [0.26 0.46 0.46]]
B1:  [[0.71]
 [0.62]]
W2:  [[7.15 6.45]
 [7.25 6.55]
 [7.35 6.65]]
B2:  [[13.15]
 [13.25]
 [13.35]]
W3:  [[42.12 42.32 42.52]
 [42.22 42.42 42.62]]
B3:  [[1.12]
 [1.22]]
W4:  [[1.682 1.882]]
B4:  [[-0.218]]
#################################
second iteration:
W1:  [[0.17 0.37 0.57]
 [0.26 0.46 0.46]]
B1:  [[0.71]
 [0.62]]
W2:  [[7.15 6.45]
 [7.25 6.55]
 [7.35 6.65]]
B2:  [[13.15]
 [13.25]
 [13.35]]
W3:  [[42.12 42.32 42.52]
 [42.22 42.42 42.62]]
B3:  [[1.12]
 [1.22]]
W4:  [[1.9474 2.1474]]
B4:  [[0.0474]]
#################################
